#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_COLON_EQ = 4,
  anon_sym_COLON_COLON = 5,
  sym_identifier = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_DASH_GT = 9,
  anon_sym_COMMA = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym__ = 13,
  anon_sym_PLUS_PLUS = 14,
  anon_sym_DASH_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_AMP = 17,
  anon_sym_TILDE = 18,
  anon_sym_DOLLAR = 19,
  anon_sym_DOT_DOT_DOT = 20,
  anon_sym_DASH = 21,
  anon_sym_PLUS = 22,
  anon_sym_BANG = 23,
  anon_sym_DOT = 24,
  anon_sym_DOT_DOT = 25,
  anon_sym_return = 26,
  sym_number = 27,
  sym_string = 28,
  sym_float = 29,
  anon_sym_true = 30,
  anon_sym_false = 31,
  sym_source_file = 32,
  sym_declaration = 33,
  sym_assignment = 34,
  sym_any_identifier = 35,
  sym_namespaced_identifier = 36,
  sym_type = 37,
  sym_function_type = 38,
  sym_parameters = 39,
  sym_parameter = 40,
  sym_definition = 41,
  sym_block = 42,
  sym_statement = 43,
  sym_expression = 44,
  sym_unary_expression = 45,
  sym_unary_postfix_expression = 46,
  sym_unary_prefix_expression = 47,
  sym_function_call = 48,
  sym_method_call = 49,
  sym_arguments = 50,
  sym_return_statement = 51,
  sym_literal = 52,
  sym_boolean = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_parameters_repeat1 = 55,
  aux_sym_block_repeat1 = 56,
  aux_sym_arguments_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_COLON_COLON] = "::",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym__] = "_",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_STAR] = "*",
  [anon_sym_AMP] = "&",
  [anon_sym_TILDE] = "~",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_return] = "return",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_assignment] = "assignment",
  [sym_any_identifier] = "any_identifier",
  [sym_namespaced_identifier] = "namespaced_identifier",
  [sym_type] = "type",
  [sym_function_type] = "function_type",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_definition] = "definition",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_unary_expression] = "unary_expression",
  [sym_unary_postfix_expression] = "unary_postfix_expression",
  [sym_unary_prefix_expression] = "unary_prefix_expression",
  [sym_function_call] = "function_call",
  [sym_method_call] = "method_call",
  [sym_arguments] = "arguments",
  [sym_return_statement] = "return_statement",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym__] = anon_sym__,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_return] = anon_sym_return,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_assignment] = sym_assignment,
  [sym_any_identifier] = sym_any_identifier,
  [sym_namespaced_identifier] = sym_namespaced_identifier,
  [sym_type] = sym_type,
  [sym_function_type] = sym_function_type,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_definition] = sym_definition,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_unary_postfix_expression] = sym_unary_postfix_expression,
  [sym_unary_prefix_expression] = sym_unary_prefix_expression,
  [sym_function_call] = sym_function_call,
  [sym_method_call] = sym_method_call,
  [sym_arguments] = sym_arguments,
  [sym_return_statement] = sym_return_statement,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_any_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_namespaced_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_postfix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '!', 48,
        '"', 2,
        '$', 43,
        '&', 41,
        '(', 31,
        ')', 32,
        '*', 40,
        '+', 47,
        ',', 34,
        '-', 46,
        '.', 49,
        ':', 13,
        ';', 12,
        '=', 15,
        '_', 37,
        'f', 18,
        'r', 19,
        't', 24,
        '{', 35,
        '}', 36,
        '~', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 48,
        '"', 2,
        ')', 32,
        '+', 47,
        '-', 45,
        ':', 5,
        'f', 18,
        't', 24,
        '{', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '$', 43,
        '&', 41,
        '(', 31,
        ')', 32,
        '*', 40,
        '+', 3,
        ',', 34,
        '-', 4,
        '.', 49,
        ':', 5,
        ';', 12,
        '=', 15,
        '~', 42,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym__);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      if (lookahead == '.') ADVANCE(44);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 10},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 10},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 10},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 10},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(74),
    [sym_declaration] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(26), 1,
      sym_expression,
    STATE(60), 1,
      sym_definition,
    STATE(61), 1,
      sym_block,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [52] = 14,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(26), 1,
      sym_expression,
    STATE(54), 1,
      sym_definition,
    STATE(61), 1,
      sym_block,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [104] = 13,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(27), 1,
      sym_expression,
    STATE(72), 1,
      sym_arguments,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [153] = 13,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(27), 1,
      sym_expression,
    STATE(73), 1,
      sym_arguments,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [202] = 11,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(32), 1,
      sym_expression,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [245] = 11,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(33), 1,
      sym_expression,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [288] = 11,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(29), 1,
      sym_expression,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [331] = 11,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(17), 1,
      sym_number,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(17), 1,
      sym_boolean,
    STATE(24), 1,
      sym_expression,
    ACTIONS(19), 2,
      sym_string,
      sym_float,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(15), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(19), 5,
      sym_any_identifier,
      sym_unary_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [374] = 3,
    ACTIONS(29), 1,
      anon_sym_COLON_COLON,
    ACTIONS(31), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(27), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [398] = 3,
    ACTIONS(29), 1,
      anon_sym_COLON_COLON,
    ACTIONS(35), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(33), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [422] = 3,
    ACTIONS(29), 1,
      anon_sym_COLON_COLON,
    ACTIONS(39), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(37), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [446] = 2,
    ACTIONS(35), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(33), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [467] = 2,
    ACTIONS(39), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(37), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [488] = 2,
    ACTIONS(31), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(27), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [509] = 2,
    ACTIONS(43), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(41), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [529] = 2,
    ACTIONS(47), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(45), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [549] = 2,
    ACTIONS(51), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(49), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [569] = 2,
    ACTIONS(55), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(53), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [589] = 2,
    ACTIONS(59), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(57), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [609] = 2,
    ACTIONS(63), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(61), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [629] = 2,
    ACTIONS(67), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(65), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [649] = 2,
    ACTIONS(71), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(69), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [669] = 2,
    ACTIONS(75), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(73), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [689] = 2,
    ACTIONS(79), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(77), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [709] = 4,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
    ACTIONS(85), 7,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [731] = 6,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(87), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(85), 7,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [757] = 9,
    ACTIONS(93), 1,
      anon_sym_SEMI,
    ACTIONS(96), 1,
      anon_sym_COLON_COLON,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 1,
      anon_sym_return,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(69), 1,
      sym_any_identifier,
    STATE(28), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(70), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [788] = 4,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(87), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(107), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(85), 7,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [809] = 9,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(109), 1,
      anon_sym_SEMI,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      anon_sym_return,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(69), 1,
      sym_any_identifier,
    STATE(31), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(70), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [840] = 9,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(109), 1,
      anon_sym_SEMI,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(115), 1,
      anon_sym_return,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(69), 1,
      sym_any_identifier,
    STATE(28), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(70), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [871] = 4,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    ACTIONS(87), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(85), 7,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [891] = 4,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_SEMI,
    ACTIONS(87), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(85), 7,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
  [911] = 6,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(66), 1,
      sym_type,
    STATE(42), 2,
      sym_any_identifier,
      sym_function_type,
  [931] = 6,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(50), 1,
      sym_type,
    STATE(42), 2,
      sym_any_identifier,
      sym_function_type,
  [951] = 6,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(40), 1,
      sym_type,
    STATE(42), 2,
      sym_any_identifier,
      sym_function_type,
  [971] = 2,
    ACTIONS(129), 1,
      anon_sym_DASH_GT,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [983] = 6,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(41), 1,
      sym_type,
    STATE(42), 2,
      sym_any_identifier,
      sym_function_type,
  [1003] = 2,
    ACTIONS(133), 1,
      anon_sym_DASH_GT,
    ACTIONS(131), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1015] = 1,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1024] = 1,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1033] = 1,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1042] = 4,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    ACTIONS(146), 1,
      sym_identifier,
    STATE(43), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1056] = 2,
    ACTIONS(151), 2,
      sym_identifier,
      anon_sym_return,
    ACTIONS(149), 3,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
      anon_sym_RBRACE,
  [1066] = 4,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      anon_sym_SEMI,
    STATE(43), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1080] = 2,
    ACTIONS(159), 2,
      sym_identifier,
      anon_sym_return,
    ACTIONS(157), 3,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
      anon_sym_RBRACE,
  [1090] = 4,
    ACTIONS(29), 1,
      anon_sym_COLON_COLON,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(161), 1,
      anon_sym_COLON,
    ACTIONS(163), 1,
      anon_sym_COLON_EQ,
  [1103] = 4,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(14), 1,
      sym_namespaced_identifier,
    STATE(71), 1,
      sym_any_identifier,
  [1116] = 4,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_parameter,
    STATE(68), 1,
      sym_parameters,
  [1129] = 2,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1138] = 3,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(13), 1,
      sym_namespaced_identifier,
  [1148] = 3,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parameters_repeat1,
  [1158] = 1,
    ACTIONS(180), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1164] = 1,
    ACTIONS(182), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1170] = 3,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parameters_repeat1,
  [1180] = 3,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_parameters_repeat1,
  [1190] = 3,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_arguments_repeat1,
  [1200] = 1,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1206] = 3,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_arguments_repeat1,
  [1216] = 1,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1222] = 1,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1228] = 3,
    ACTIONS(9), 1,
      anon_sym_COLON_COLON,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(15), 1,
      sym_namespaced_identifier,
  [1238] = 2,
    ACTIONS(161), 1,
      anon_sym_COLON,
    ACTIONS(163), 1,
      anon_sym_COLON_EQ,
  [1245] = 2,
    ACTIONS(165), 1,
      sym_identifier,
    STATE(65), 1,
      sym_parameter,
  [1252] = 1,
    ACTIONS(175), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1257] = 1,
    ACTIONS(199), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1262] = 1,
    ACTIONS(201), 1,
      anon_sym_COLON,
  [1266] = 1,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
  [1270] = 1,
    ACTIONS(205), 1,
      anon_sym_EQ,
  [1274] = 1,
    ACTIONS(207), 1,
      anon_sym_SEMI,
  [1278] = 1,
    ACTIONS(209), 1,
      anon_sym_LPAREN,
  [1282] = 1,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [1286] = 1,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
  [1290] = 1,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 245,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 331,
  [SMALL_STATE(10)] = 374,
  [SMALL_STATE(11)] = 398,
  [SMALL_STATE(12)] = 422,
  [SMALL_STATE(13)] = 446,
  [SMALL_STATE(14)] = 467,
  [SMALL_STATE(15)] = 488,
  [SMALL_STATE(16)] = 509,
  [SMALL_STATE(17)] = 529,
  [SMALL_STATE(18)] = 549,
  [SMALL_STATE(19)] = 569,
  [SMALL_STATE(20)] = 589,
  [SMALL_STATE(21)] = 609,
  [SMALL_STATE(22)] = 629,
  [SMALL_STATE(23)] = 649,
  [SMALL_STATE(24)] = 669,
  [SMALL_STATE(25)] = 689,
  [SMALL_STATE(26)] = 709,
  [SMALL_STATE(27)] = 731,
  [SMALL_STATE(28)] = 757,
  [SMALL_STATE(29)] = 788,
  [SMALL_STATE(30)] = 809,
  [SMALL_STATE(31)] = 840,
  [SMALL_STATE(32)] = 871,
  [SMALL_STATE(33)] = 891,
  [SMALL_STATE(34)] = 911,
  [SMALL_STATE(35)] = 931,
  [SMALL_STATE(36)] = 951,
  [SMALL_STATE(37)] = 971,
  [SMALL_STATE(38)] = 983,
  [SMALL_STATE(39)] = 1003,
  [SMALL_STATE(40)] = 1015,
  [SMALL_STATE(41)] = 1024,
  [SMALL_STATE(42)] = 1033,
  [SMALL_STATE(43)] = 1042,
  [SMALL_STATE(44)] = 1056,
  [SMALL_STATE(45)] = 1066,
  [SMALL_STATE(46)] = 1080,
  [SMALL_STATE(47)] = 1090,
  [SMALL_STATE(48)] = 1103,
  [SMALL_STATE(49)] = 1116,
  [SMALL_STATE(50)] = 1129,
  [SMALL_STATE(51)] = 1138,
  [SMALL_STATE(52)] = 1148,
  [SMALL_STATE(53)] = 1158,
  [SMALL_STATE(54)] = 1164,
  [SMALL_STATE(55)] = 1170,
  [SMALL_STATE(56)] = 1180,
  [SMALL_STATE(57)] = 1190,
  [SMALL_STATE(58)] = 1200,
  [SMALL_STATE(59)] = 1206,
  [SMALL_STATE(60)] = 1216,
  [SMALL_STATE(61)] = 1222,
  [SMALL_STATE(62)] = 1228,
  [SMALL_STATE(63)] = 1238,
  [SMALL_STATE(64)] = 1245,
  [SMALL_STATE(65)] = 1252,
  [SMALL_STATE(66)] = 1257,
  [SMALL_STATE(67)] = 1262,
  [SMALL_STATE(68)] = 1266,
  [SMALL_STATE(69)] = 1270,
  [SMALL_STATE(70)] = 1274,
  [SMALL_STATE(71)] = 1278,
  [SMALL_STATE(72)] = 1282,
  [SMALL_STATE(73)] = 1286,
  [SMALL_STATE(74)] = 1290,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespaced_identifier, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespaced_identifier, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespaced_identifier, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespaced_identifier, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_identifier, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_identifier, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 6, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 6, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_postfix_expression, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_postfix_expression, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_prefix_expression, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_prefix_expression, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [215] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cpp2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
