#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 84
#define ALIAS_COUNT 0
#define TOKEN_COUNT 56
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_COLON_EQ = 4,
  anon_sym_STAR_EQ = 5,
  anon_sym_SLASH_EQ = 6,
  anon_sym_PERCENT_EQ = 7,
  anon_sym_PLUS_EQ = 8,
  anon_sym_DASH_EQ = 9,
  anon_sym_GT_GT_EQ = 10,
  anon_sym_LT_LT_EQ = 11,
  anon_sym_AMP_EQ = 12,
  anon_sym_CARET_EQ = 13,
  anon_sym_PIPE_EQ = 14,
  anon_sym_COLON_COLON = 15,
  sym_identifier = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_DASH_GT = 19,
  anon_sym_COMMA = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym__ = 23,
  anon_sym_PLUS_PLUS = 24,
  anon_sym_DASH_DASH = 25,
  anon_sym_STAR = 26,
  anon_sym_AMP = 27,
  anon_sym_TILDE = 28,
  anon_sym_DOLLAR = 29,
  anon_sym_DOT_DOT_DOT = 30,
  anon_sym_DASH = 31,
  anon_sym_PLUS = 32,
  anon_sym_BANG = 33,
  anon_sym_SLASH = 34,
  anon_sym_PERCENT = 35,
  anon_sym_LT_LT = 36,
  anon_sym_GT_GT = 37,
  anon_sym_LT_EQ_GT = 38,
  anon_sym_LT = 39,
  anon_sym_GT = 40,
  anon_sym_LT_EQ = 41,
  anon_sym_GT_EQ = 42,
  anon_sym_EQ_EQ = 43,
  anon_sym_BANG_EQ = 44,
  anon_sym_CARET = 45,
  anon_sym_PIPE = 46,
  anon_sym_PIPE_PIPE = 47,
  anon_sym_DOT = 48,
  anon_sym_DOT_DOT = 49,
  anon_sym_return = 50,
  sym_number = 51,
  sym_string = 52,
  sym_float = 53,
  anon_sym_true = 54,
  anon_sym_false = 55,
  sym_source_file = 56,
  sym_declaration = 57,
  sym_assignment = 58,
  sym_any_identifier = 59,
  sym_namespaced_identifier = 60,
  sym_type = 61,
  sym_function_type = 62,
  sym_parameters = 63,
  sym_parameter = 64,
  sym_definition = 65,
  sym_block = 66,
  sym_statement = 67,
  sym_expression = 68,
  sym_unary_expression = 69,
  sym_unary_postfix_expression = 70,
  sym_unary_prefix_expression = 71,
  sym_binary_expression = 72,
  sym_parenthese_expression = 73,
  sym_function_call = 74,
  sym_method_call = 75,
  sym_arguments = 76,
  sym_return_statement = 77,
  sym_literal = 78,
  sym_boolean = 79,
  aux_sym_source_file_repeat1 = 80,
  aux_sym_parameters_repeat1 = 81,
  aux_sym_block_repeat1 = 82,
  aux_sym_arguments_repeat1 = 83,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_GT_GT_EQ] = ">>=",
  [anon_sym_LT_LT_EQ] = "<<=",
  [anon_sym_AMP_EQ] = "&=",
  [anon_sym_CARET_EQ] = "^=",
  [anon_sym_PIPE_EQ] = "|=",
  [anon_sym_COLON_COLON] = "::",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym__] = "_",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_STAR] = "*",
  [anon_sym_AMP] = "&",
  [anon_sym_TILDE] = "~",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_BANG] = "!",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_CARET] = "^",
  [anon_sym_PIPE] = "|",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_return] = "return",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_assignment] = "assignment",
  [sym_any_identifier] = "any_identifier",
  [sym_namespaced_identifier] = "namespaced_identifier",
  [sym_type] = "type",
  [sym_function_type] = "function_type",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_definition] = "definition",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_unary_expression] = "unary_expression",
  [sym_unary_postfix_expression] = "unary_postfix_expression",
  [sym_unary_prefix_expression] = "unary_prefix_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_parenthese_expression] = "parenthese_expression",
  [sym_function_call] = "function_call",
  [sym_method_call] = "method_call",
  [sym_arguments] = "arguments",
  [sym_return_statement] = "return_statement",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_GT_GT_EQ] = anon_sym_GT_GT_EQ,
  [anon_sym_LT_LT_EQ] = anon_sym_LT_LT_EQ,
  [anon_sym_AMP_EQ] = anon_sym_AMP_EQ,
  [anon_sym_CARET_EQ] = anon_sym_CARET_EQ,
  [anon_sym_PIPE_EQ] = anon_sym_PIPE_EQ,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym__] = anon_sym__,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_return] = anon_sym_return,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_assignment] = sym_assignment,
  [sym_any_identifier] = sym_any_identifier,
  [sym_namespaced_identifier] = sym_namespaced_identifier,
  [sym_type] = sym_type,
  [sym_function_type] = sym_function_type,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_definition] = sym_definition,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_unary_postfix_expression] = sym_unary_postfix_expression,
  [sym_unary_prefix_expression] = sym_unary_prefix_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_parenthese_expression] = sym_parenthese_expression,
  [sym_function_call] = sym_function_call,
  [sym_method_call] = sym_method_call,
  [sym_arguments] = sym_arguments,
  [sym_return_statement] = sym_return_statement,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_any_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_namespaced_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_function_type] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_postfix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_prefix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthese_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 5,
  [39] = 4,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 7,
  [44] = 6,
  [45] = 45,
  [46] = 8,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 67,
  [74] = 74,
  [75] = 75,
  [76] = 66,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '!', 78,
        '"', 2,
        '$', 69,
        '%', 82,
        '&', 67,
        '(', 57,
        ')', 58,
        '*', 66,
        '+', 76,
        ',', 60,
        '-', 73,
        '.', 101,
        '/', 80,
        ':', 28,
        ';', 27,
        '<', 88,
        '=', 31,
        '>', 90,
        '^', 97,
        '_', 63,
        'f', 44,
        'r', 45,
        't', 50,
        '{', 61,
        '|', 98,
        '}', 62,
        '~', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 77,
        '"', 2,
        '(', 57,
        ')', 58,
        '+', 74,
        '-', 71,
        ':', 4,
        'f', 44,
        't', 50,
        '{', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(105);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '%', 7,
        '&', 16,
        '*', 17,
        '+', 8,
        '-', 9,
        '/', 10,
        ':', 28,
        ';', 27,
        '<', 5,
        '=', 30,
        '>', 19,
        '^', 12,
        'r', 45,
        '|', 13,
        '}', 62,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '<') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(94);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(59);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 22:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '!', 78,
        '"', 2,
        '$', 69,
        '%', 81,
        '&', 67,
        '(', 57,
        ')', 58,
        '*', 66,
        '+', 75,
        ',', 60,
        '-', 72,
        '.', 101,
        '/', 79,
        ':', 4,
        ';', 27,
        '<', 89,
        '=', 11,
        '>', 91,
        '^', 96,
        'f', 44,
        't', 50,
        '|', 99,
        '~', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 23:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '!', 6,
        '$', 69,
        '%', 81,
        '&', 67,
        '(', 57,
        ')', 58,
        '*', 66,
        '+', 75,
        ',', 60,
        '-', 72,
        '.', 101,
        '/', 79,
        ':', 4,
        ';', 27,
        '<', 89,
        '=', 31,
        '>', 91,
        '^', 96,
        '|', 99,
        '~', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '!', 6,
        '$', 69,
        '%', 81,
        '&', 67,
        '(', 57,
        ')', 58,
        '*', 66,
        '+', 75,
        ',', 60,
        '-', 72,
        '.', 101,
        '/', 79,
        ':', 29,
        ';', 27,
        '<', 89,
        '=', 11,
        '>', 91,
        '^', 96,
        '|', 99,
        '~', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      if (lookahead == ')') ADVANCE(58);
      if (lookahead == ',') ADVANCE(60);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(94);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT_GT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_LT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AMP_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_CARET_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PIPE_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym__);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(65);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(65);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(59);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(64);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(64);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(84);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(83);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(93);
      if (lookahead == '>') ADVANCE(86);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(93);
      if (lookahead == '>') ADVANCE(85);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(87);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '=') ADVANCE(42);
      if (lookahead == '|') ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      if (lookahead == '.') ADVANCE(70);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 23},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 24},
  [10] = {.lex_state = 24},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 24},
  [14] = {.lex_state = 24},
  [15] = {.lex_state = 24},
  [16] = {.lex_state = 24},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 24},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 25},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 23},
  [50] = {.lex_state = 25},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 25},
  [54] = {.lex_state = 25},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 23},
  [61] = {.lex_state = 25},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 23},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 23},
  [67] = {.lex_state = 23},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 23},
  [74] = {.lex_state = 23},
  [75] = {.lex_state = 23},
  [76] = {.lex_state = 23},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 24},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 24},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_GT_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT_EQ] = ACTIONS(1),
    [anon_sym_CARET_EQ] = ACTIONS(1),
    [anon_sym_PIPE_EQ] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(83),
    [sym_declaration] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
  [2] = {
    [sym_any_identifier] = STATE(18),
    [sym_namespaced_identifier] = STATE(8),
    [sym_expression] = STATE(11),
    [sym_unary_expression] = STATE(18),
    [sym_unary_postfix_expression] = STATE(10),
    [sym_unary_prefix_expression] = STATE(10),
    [sym_binary_expression] = STATE(18),
    [sym_parenthese_expression] = STATE(18),
    [sym_function_call] = STATE(18),
    [sym_method_call] = STATE(18),
    [sym_literal] = STATE(18),
    [sym_boolean] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(9),
    [anon_sym_COLON_COLON] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_PLUS_PLUS] = ACTIONS(9),
    [anon_sym_DASH_DASH] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_BANG] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(9),
    [anon_sym_LT_LT] = ACTIONS(9),
    [anon_sym_GT_GT] = ACTIONS(9),
    [anon_sym_LT_EQ_GT] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(19),
    [anon_sym_GT_EQ] = ACTIONS(9),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(19),
    [anon_sym_PIPE_PIPE] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(23),
    [sym_float] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(31), 1,
      anon_sym_COLON_COLON,
    ACTIONS(29), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(27), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [40] = 3,
    ACTIONS(31), 1,
      anon_sym_COLON_COLON,
    ACTIONS(35), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(33), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [80] = 3,
    ACTIONS(31), 1,
      anon_sym_COLON_COLON,
    ACTIONS(39), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(37), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [120] = 2,
    ACTIONS(35), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(33), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [157] = 2,
    ACTIONS(39), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(37), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [194] = 2,
    ACTIONS(29), 9,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(27), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [231] = 2,
    ACTIONS(43), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(41), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [267] = 2,
    ACTIONS(47), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(45), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [303] = 2,
    ACTIONS(51), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(49), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [339] = 2,
    ACTIONS(55), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(53), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [375] = 6,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(67), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [419] = 2,
    ACTIONS(71), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(69), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [455] = 2,
    ACTIONS(75), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(73), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [491] = 2,
    ACTIONS(79), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(77), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [527] = 2,
    ACTIONS(83), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(81), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [563] = 2,
    ACTIONS(87), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(85), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [599] = 2,
    ACTIONS(19), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(9), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [635] = 2,
    ACTIONS(91), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(89), 23,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_STAR,
      anon_sym_AMP,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [671] = 9,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [719] = 7,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [763] = 7,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(103), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [806] = 7,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_SEMI,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [848] = 7,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_SEMI,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [890] = 7,
    ACTIONS(93), 1,
      anon_sym_LPAREN,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(61), 2,
      anon_sym_STAR,
      anon_sym_AMP,
    ACTIONS(99), 2,
      anon_sym_DOT,
      anon_sym_DOT_DOT,
    ACTIONS(59), 5,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
      anon_sym_TILDE,
      anon_sym_DOLLAR,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(63), 6,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(65), 10,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_LT_EQ_GT,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_CARET,
      anon_sym_PIPE_PIPE,
  [932] = 15,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(22), 1,
      sym_expression,
    STATE(63), 1,
      sym_block,
    STATE(69), 1,
      sym_definition,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [989] = 15,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(22), 1,
      sym_expression,
    STATE(63), 1,
      sym_block,
    STATE(74), 1,
      sym_definition,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1046] = 14,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(21), 1,
      sym_expression,
    STATE(82), 1,
      sym_arguments,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1100] = 14,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(21), 1,
      sym_expression,
    STATE(87), 1,
      sym_arguments,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1154] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(11), 1,
      sym_expression,
    STATE(16), 1,
      sym_boolean,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1202] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(24), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1250] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(25), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1298] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(13), 1,
      sym_expression,
    STATE(16), 1,
      sym_boolean,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1346] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(23), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1394] = 12,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(16), 1,
      sym_boolean,
    STATE(26), 1,
      sym_expression,
    ACTIONS(23), 2,
      sym_string,
      sym_float,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_unary_postfix_expression,
      sym_unary_prefix_expression,
    ACTIONS(113), 3,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_BANG,
    STATE(18), 7,
      sym_any_identifier,
      sym_unary_expression,
      sym_binary_expression,
      sym_parenthese_expression,
      sym_function_call,
      sym_method_call,
      sym_literal,
  [1442] = 4,
    ACTIONS(119), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      anon_sym_COLON_EQ,
    ACTIONS(123), 1,
      anon_sym_COLON_COLON,
    ACTIONS(27), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1465] = 2,
    ACTIONS(123), 1,
      anon_sym_COLON_COLON,
    ACTIONS(37), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1482] = 2,
    ACTIONS(123), 1,
      anon_sym_COLON_COLON,
    ACTIONS(33), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1499] = 9,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(127), 1,
      anon_sym_COLON_COLON,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(133), 1,
      anon_sym_return,
    STATE(45), 1,
      sym_any_identifier,
    STATE(46), 1,
      sym_namespaced_identifier,
    STATE(42), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(85), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [1530] = 9,
    ACTIONS(125), 1,
      anon_sym_SEMI,
    ACTIONS(127), 1,
      anon_sym_COLON_COLON,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(133), 1,
      anon_sym_return,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym_any_identifier,
    STATE(46), 1,
      sym_namespaced_identifier,
    STATE(40), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(85), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [1561] = 9,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_COLON_COLON,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    ACTIONS(148), 1,
      anon_sym_return,
    STATE(45), 1,
      sym_any_identifier,
    STATE(46), 1,
      sym_namespaced_identifier,
    STATE(42), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(85), 3,
      sym_declaration,
      sym_assignment,
      sym_return_statement,
  [1592] = 1,
    ACTIONS(37), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1606] = 1,
    ACTIONS(33), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1620] = 1,
    ACTIONS(151), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1634] = 1,
    ACTIONS(27), 11,
      anon_sym_EQ,
      anon_sym_STAR_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_GT_GT_EQ,
      anon_sym_LT_LT_EQ,
      anon_sym_AMP_EQ,
      anon_sym_CARET_EQ,
      anon_sym_PIPE_EQ,
  [1648] = 2,
    ACTIONS(155), 1,
      anon_sym_DASH_GT,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1660] = 6,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(80), 1,
      sym_type,
    STATE(53), 2,
      sym_any_identifier,
      sym_function_type,
  [1680] = 6,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(54), 1,
      sym_type,
    STATE(53), 2,
      sym_any_identifier,
      sym_function_type,
  [1700] = 2,
    ACTIONS(163), 1,
      anon_sym_DASH_GT,
    ACTIONS(161), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1712] = 6,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(55), 1,
      sym_type,
    STATE(53), 2,
      sym_any_identifier,
      sym_function_type,
  [1732] = 6,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(61), 1,
      sym_type,
    STATE(53), 2,
      sym_any_identifier,
      sym_function_type,
  [1752] = 1,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1761] = 1,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1770] = 1,
    ACTIONS(169), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1779] = 4,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(56), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1793] = 2,
    ACTIONS(181), 2,
      sym_identifier,
      anon_sym_return,
    ACTIONS(179), 3,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
      anon_sym_RBRACE,
  [1803] = 2,
    ACTIONS(185), 2,
      sym_identifier,
      anon_sym_return,
    ACTIONS(183), 3,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
      anon_sym_RBRACE,
  [1813] = 4,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    STATE(56), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
  [1827] = 4,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(8), 1,
      sym_namespaced_identifier,
    STATE(81), 1,
      sym_any_identifier,
  [1840] = 2,
    ACTIONS(193), 1,
      anon_sym_EQ,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1849] = 4,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_parameter,
    STATE(86), 1,
      sym_parameters,
  [1862] = 1,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1868] = 3,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_arguments_repeat1,
  [1878] = 3,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_parameters_repeat1,
  [1888] = 3,
    ACTIONS(127), 1,
      anon_sym_COLON_COLON,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(43), 1,
      sym_namespaced_identifier,
  [1898] = 3,
    ACTIONS(127), 1,
      anon_sym_COLON_COLON,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(44), 1,
      sym_namespaced_identifier,
  [1908] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_parameters_repeat1,
  [1918] = 1,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1924] = 1,
    ACTIONS(212), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1930] = 3,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_parameters_repeat1,
  [1940] = 3,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_arguments_repeat1,
  [1950] = 3,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(221), 1,
      sym_identifier,
    STATE(6), 1,
      sym_namespaced_identifier,
  [1960] = 1,
    ACTIONS(223), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1966] = 1,
    ACTIONS(225), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [1972] = 3,
    ACTIONS(11), 1,
      anon_sym_COLON_COLON,
    ACTIONS(227), 1,
      sym_identifier,
    STATE(7), 1,
      sym_namespaced_identifier,
  [1982] = 1,
    ACTIONS(214), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1987] = 2,
    ACTIONS(119), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      anon_sym_COLON_EQ,
  [1994] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(77), 1,
      sym_parameter,
  [2001] = 1,
    ACTIONS(229), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2006] = 1,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
  [2010] = 1,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [2014] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [2018] = 1,
    ACTIONS(237), 1,
      anon_sym_COLON,
  [2022] = 1,
    ACTIONS(239), 1,
      anon_sym_SEMI,
  [2026] = 1,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
  [2030] = 1,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 157,
  [SMALL_STATE(8)] = 194,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 267,
  [SMALL_STATE(11)] = 303,
  [SMALL_STATE(12)] = 339,
  [SMALL_STATE(13)] = 375,
  [SMALL_STATE(14)] = 419,
  [SMALL_STATE(15)] = 455,
  [SMALL_STATE(16)] = 491,
  [SMALL_STATE(17)] = 527,
  [SMALL_STATE(18)] = 563,
  [SMALL_STATE(19)] = 599,
  [SMALL_STATE(20)] = 635,
  [SMALL_STATE(21)] = 671,
  [SMALL_STATE(22)] = 719,
  [SMALL_STATE(23)] = 763,
  [SMALL_STATE(24)] = 806,
  [SMALL_STATE(25)] = 848,
  [SMALL_STATE(26)] = 890,
  [SMALL_STATE(27)] = 932,
  [SMALL_STATE(28)] = 989,
  [SMALL_STATE(29)] = 1046,
  [SMALL_STATE(30)] = 1100,
  [SMALL_STATE(31)] = 1154,
  [SMALL_STATE(32)] = 1202,
  [SMALL_STATE(33)] = 1250,
  [SMALL_STATE(34)] = 1298,
  [SMALL_STATE(35)] = 1346,
  [SMALL_STATE(36)] = 1394,
  [SMALL_STATE(37)] = 1442,
  [SMALL_STATE(38)] = 1465,
  [SMALL_STATE(39)] = 1482,
  [SMALL_STATE(40)] = 1499,
  [SMALL_STATE(41)] = 1530,
  [SMALL_STATE(42)] = 1561,
  [SMALL_STATE(43)] = 1592,
  [SMALL_STATE(44)] = 1606,
  [SMALL_STATE(45)] = 1620,
  [SMALL_STATE(46)] = 1634,
  [SMALL_STATE(47)] = 1648,
  [SMALL_STATE(48)] = 1660,
  [SMALL_STATE(49)] = 1680,
  [SMALL_STATE(50)] = 1700,
  [SMALL_STATE(51)] = 1712,
  [SMALL_STATE(52)] = 1732,
  [SMALL_STATE(53)] = 1752,
  [SMALL_STATE(54)] = 1761,
  [SMALL_STATE(55)] = 1770,
  [SMALL_STATE(56)] = 1779,
  [SMALL_STATE(57)] = 1793,
  [SMALL_STATE(58)] = 1803,
  [SMALL_STATE(59)] = 1813,
  [SMALL_STATE(60)] = 1827,
  [SMALL_STATE(61)] = 1840,
  [SMALL_STATE(62)] = 1849,
  [SMALL_STATE(63)] = 1862,
  [SMALL_STATE(64)] = 1868,
  [SMALL_STATE(65)] = 1878,
  [SMALL_STATE(66)] = 1888,
  [SMALL_STATE(67)] = 1898,
  [SMALL_STATE(68)] = 1908,
  [SMALL_STATE(69)] = 1918,
  [SMALL_STATE(70)] = 1924,
  [SMALL_STATE(71)] = 1930,
  [SMALL_STATE(72)] = 1940,
  [SMALL_STATE(73)] = 1950,
  [SMALL_STATE(74)] = 1960,
  [SMALL_STATE(75)] = 1966,
  [SMALL_STATE(76)] = 1972,
  [SMALL_STATE(77)] = 1982,
  [SMALL_STATE(78)] = 1987,
  [SMALL_STATE(79)] = 1994,
  [SMALL_STATE(80)] = 2001,
  [SMALL_STATE(81)] = 2006,
  [SMALL_STATE(82)] = 2010,
  [SMALL_STATE(83)] = 2014,
  [SMALL_STATE(84)] = 2018,
  [SMALL_STATE(85)] = 2022,
  [SMALL_STATE(86)] = 2026,
  [SMALL_STATE(87)] = 2030,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_postfix_expression, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_postfix_expression, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_identifier, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_any_identifier, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespaced_identifier, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespaced_identifier, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespaced_identifier, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_namespaced_identifier, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_prefix_expression, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_prefix_expression, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthese_expression, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthese_expression, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 6, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 6, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_type, 5, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cpp2(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
