name: CI

on:
  push:
    branches: [main]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - test_on_cpp2_files.sh
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - test_on_cpp2_files.sh

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout tree-sitter-c
        uses: actions/checkout@v4
        with:
          repository: tree-sitter/tree-sitter-c
          path: node_modules/tree-sitter-c
          sparse-checkout: queries/
          ref: v0.21.4
      - name: Checkout tree-sitter-cpp
        uses: actions/checkout@v4
        with:
          repository: tree-sitter/tree-sitter-cpp
          path: node_modules/tree-sitter-cpp
          sparse-checkout: queries/
          ref: v0.22.3
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run tests
        uses: tree-sitter/parser-test-action@89f9071ad0c75902919524e56059c6898825343b # v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
          test-node: true
          test-python: true
          test-go: true
      - name: Clone cppfront
        run: git clone https://github.com/hsutter/cppfront.git
      - name: Find and parse cpp2 files
        run: ./test_on_cpp2_files.sh ./cppfront
